### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_USTVGO#64]
```
version: '2.1'
services:
  fhdhr_ustvgo:
    image: fhdhr_ustvgo:0.4.6
    container_name: fhdhr_ustvgo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 1900:1900 # ssd cluster port
      - 5004:5004 # web & HDHR port
    volumes:
      - /<docker-config-directory>/fhdhr_ustvgo:/app/config
    restart: always
```
